version: '3.5'
services:
  db:
    build: ./postgres
    image: gw-db
    container_name: gw-db
    #volumes:
    #  - ./postgres/data_dir/:/var/lib/postgresql/data
    ports:
      - "$POSTGRES_PORT:5432"
    env_file:
      - .env
      

  geoserver:
    image: oscarfonts/geoserver:2.21.1
    #image: kartoza/geoserver:2.18.0
    container_name: gw-geoserver
    #volumes:
    #  - ./geoserver/data_dir/:/opt/geoserver/data_dir/
    ports:
      - "$GEOSERVER_PORT:8080"
    env_file:
      - .env
    depends_on:
      - db

  app:
    build: .
    image: gw-app
    container_name: gw-app
    working_dir: /app/
    environment:
      - RACK_ENV
      - VIRTUAL_HOST
    ports:
      - "$APP_PORT:3000"
    #volumes:
    # - .:/opt/geoworks
    env_file:
      - .env
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 45s
      timeout: 10s
      retries: 3
      start_period: 5s

  nginx:
    image: gw-nginx:latest
    container_name: gw-nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped
