version: '3.5'
services:
  db:
    build: ./postgres
    image: gw-db
    container_name: gw-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    env_file:
      - .env
  geoserver:
    image: kartoza/geoserver:2.18.0
    container_name: gw-geoserver
    volumes:
      - ./geoserver/data_dir/:/opt/geoserver/data_dir/
    ports:
      - "$GEOSERVER_PORT:8080"
    env_file:
      - .env
    depends_on:
      - db
  app:
    build: .
    image: gw-app
    container_name: gw-app
    ports:
      - "$APP_PORT:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
     - .:/opt/geoworks
    env_file:
      - .env
    depends_on:
      - db
volumes:
  dbdata:
networks:
  default:
    name: geoworks_network
