version: '3'
services:
  db:
    build: ./postgres
    image: gw-db
    container_name: gw-db
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5555:5432"
    env_file:
      - docker-env/db.env
  geoserver:
    image: kartoza/geoserver:2.15.0
    container_name: gw-geoserver
    volumes:
      - ./geoserver/data_dir/:/opt/geoserver/data_dir/
    ports:
      - "8080:8080"
    env_file:
      - docker-env/geoserver.env
    depends_on:
      - db
  app:
    build: .
    image: gw-app
    container_name: gw-app
    ports:
      - "3000:3000"
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
     - .:/opt/geoworks
    depends_on:
      - db
volumes:
  dbdata:
